### ISSUE TITLE
Implement ANC profile page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#10]
<img width="330" alt="Screen Shot 2019-05-08 at 9 27 23 AM" src="https://user-images.githubusercontent.com/3488986/57354190-923a9000-7173-11e9-9e0e-3a4bcbfc8900.png">

- [x] Back arrow or device back button takes user to the previous page they were viewing. If coming from the family profile page, the label should be "Return to family members"; if coming from the ANC register list, the label should be "Return to all ANC women"
- [x] Top right 3 dots menu opens menu of options (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/32)
- [x] Avatar or image of the woman if taken in registration form
- [x] {first_name} {middle_name} {surname}, {age}
- [x] GA: {gest_age} weeks [interpunct] {village_town} [interpunct] ID: {opensrp_id}
- [x] Record ANC visit button row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/33)
- [x] Medical history row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/13)
- [x] Upcoming services row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/14)
- [x] Family has services due/overdue row (already implemented)
- [x] Call FAB (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/34)

------------------------------------------------------------------------------------------------------
- [x] **BA is the same**: Back arrow or device back button takes user to the previous page they were viewing. If coming from the family profile page, the label should be "Return to family members"; if coming from the ANC register list, the label should be "Return to all ANC women" 
- [x] **BA is the same**: Top right 3 dots menu opens menu of options (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/32)
- [x] **BA is the same**: Avatar or image of the woman if taken in registration form
- [x] **BA is the same**: {first_name} {middle_name} {surname}, {age}
- [x] **BA uses different field names. See the bolded value for difference.**: GA: {gest_age} weeks [interpunct] **{fam_village}** [interpunct] ID: {opensrp_id}
- [x] **BA is the same**: Record ANC visit button row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/33)
- [ ] **BA is the same**: Medical history row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/13)
- [ ] **BA is the same**: Upcoming services row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/14)
- [ ] **BA is the same**: Family has services due/overdue row (already implemented)
- [x] **BA is the same**: Call FAB (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/34)

**Comment by cagulas** [comment]
QA 6 June: 

![Screenshot_20190607-104156](https://user-images.githubusercontent.com/3488986/59088837-4ebd7800-8911-11e9-9009-f783c76fdb23.jpg)

**Comment by msschroeder** [comment]
QA June 6 build:
![Screenshot_20190611-095712](https://user-images.githubusercontent.com/20777928/59250380-c4865400-8c2f-11e9-9e45-7a9e4f9c7a79.png)

**Comment by cafootitt** [comment]
Everything above lgtm.

Waiting on: 
Record ANC visit button row (#33), Medical history row (#13), Upcoming services row (#14), Family has services due/overdue row (already implemented), and Call FAB
to be implemented

**Comment by cafootitt** [comment]
Closing this issue. The remaining issues are still pending are: #33, #52, #53
