### ISSUE TITLE
Implement ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#11]
Implement the components of the ANC home visit:

- [x] UI (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/21)
- [x] Danger signs task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/18)
- [x] ANC counseling task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/19)
- [x] Sleeping under a LLITN task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/20)
- [x] ANC card task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/22)
- [x] ANC [1-8] health facility visit task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/23)
- [x] ANC health facility visit task schedule (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/24)
- [x] TT [1-5] immunization task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/25)
- [x] TT vaccination schedule (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/26)
- [x] IPTp-SP [1st, 2nd, 3rd] dose task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/27)
- [x] IPTp-SP schedules (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/28)
- [x] Observations & Illness - optional task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/29)
- [x] Icon statuses for completed tasks (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/30)

------------------------------------------------------------------------------------------------------
Implement the components of the ANC home visit for **BA**:
- [x] UI (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/21)
- [x] Danger signs task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/18)
- [x] ANC [1-8] health facility visit task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/23)
- [x] ANC health facility visit task schedule (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/24)
- [x] Family planning task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/39)
- [x] Nutrition status task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/40)
- [x] Counseling task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/41)
- [x] Malaria prevention task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/42)
- [x] Observations & Illness - optional task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/29)
- [x] Remarks/Comments - optional task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/43)
- [x] Icon statuses for completed tasks (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/30)

**Comment by cafootitt** [comment]
Closing this, nothing to QA, since this was an epic issue.
