### ISSUE TITLE
Implement the PNC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#15]
Implement the components of the PNC home visit:

- [x] Danger signs - mother (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/84)
- [x] Danger signs - baby (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/85)
- [x] PNC health facility visit - day 1, 7, 42 (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/178)
- [x] Child vaccine card received (no issue created, same as in Child Home Visit)
- [x] Immunizations (at birth) (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/91)
- [x] Umbilical cord care (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/181)
- [ ] Exclusive breastfeeding (no issue created, same as in Child Home Visit)
- [x] Kangeroo mother care (KNC) (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/182)
- [x] Family planning (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/90)
- [x] Observations & illness - mother _- optional_ (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/96)
- [x] Observations & illness - baby _- optional_ (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/97)

- [x] Child vaccine card received, Immunizations (at birth), Exclusive breastfeeding, Observations & illness - baby tasks should expire at 28 days of age, simultaneously when the child graduates PNC to the child register.

------------------------------------------------------------------------------------------------------

Implement the components of the PNC home visit:

- [x] Danger signs - mother (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/84)
- [x] Danger signs - baby (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/85)
- [x] PNC health facility visit - within 48 hours (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/86)
- [x] PNC health facility visit - days 3 - 7 (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/87)
- [x] PNC health facility visit - days 8 - 28 (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/88)
- [x] PNC health facility visit - days 29 - 42 (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/89)
- [x] Family planning (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/90)
- [x] Immunizations (at birth) (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/91)
- [ ] Exclusive breastfeeding 0 months (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/92)
- [x] Counselling (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/93)
- [x] Nutrition status (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/94)
- [x] Malaria prevention (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/95)
- [x] Observations & illness - mother _- optional_ (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/96)
- [x] Observations & illness - baby _- optional_ (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/97)

- [x] Danger signs - baby, Immunizations (at birth), Exclusive breastfeeding, Observations & illness - baby tasks should expire at 28 days of age, simultaneously when the child graduates PNC to the child register.

**Comment by cafootitt** [comment]
@msschroeder We need to mark the services for children that will need to "expire" from the PNC home visit at 28 days when the child also moves to the child register.

**Comment by msschroeder** [comment]
@cafootitt Great! Thanks!

**Comment by cafootitt** [comment]
Closing this, as it was just the epic issue. QA results will go into the respective individual issues.
