### ISSUE TITLE
Discussion: Will there be differences between Stillbirth and Livebirth homevisits?

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#159]
As the home visits will be different for a mother with a stillbirth and a mother with a live birth, will we need a different home visit and what would this look like?

WCARO current home visit:
Implement the components of the PNC home visit:

- [ ] Danger signs - mother (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/84)
- [ ] Danger signs - baby (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/85)
- [ ] PNC health facility visit - day 1
- [ ] PNC health facility visit - day 7
- [ ] PNC health facility visit - day 42
- [ ] Child vaccine card received
- [ ] Immunizations (at birth)
- [ ] Umbilical cord care
- [ ] Exclusive breastfeeding
- [ ] Kangeroo mother care (KNC)
- [ ] Family planning (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/90)
- [ ] Observations & illness - mother _- optional_ (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/96)
- [ ] Observations & illness - baby _- optional_ (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/97)
@cafootitt Can you please add links to the PNC home visit tasks

-----------------------------------------------------------------------------------------------

BA
Components to include in the home visit could be:

- [ ] Danger signs - mother (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/84)
- [ ] PNC health facility visit - within 48 hours (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/86)
- [ ] PNC health facility visit - days 3 - 7 (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/87)
- [ ] PNC health facility visit - days 8 - 28 (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/88)
- [ ] PNC health facility visit - days 29 - 42 (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/89)
- [ ] Family planning (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/90)
- [ ] Counselling (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/93)
- [ ] Nutrition status (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/94)
- [ ] Malaria prevention (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/95)
- [ ] Observations & illness - mother _- optional_ (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/96)

And we may need to add relevance to the data dictionary to account for this.

**Comment by rowo** [comment]
@msschroeder Is this issue just about selecting which components are removed and identifying ones that might be added/edited to account for a stillbirth scenario? Because, if it's in scope to do so, it seems clear the content would be different.

**Comment by cafootitt** [comment]
@msschroeder What do you mean by "will we need a different home visit and what would this look like?"

I think the tasks within the home visit are pretty obvious for whether it's a stillbirth (e.g. no baby tasks) vs. live birth (has baby tasks). Do you want me to mark which ones wouldn't be relevant for a stillbirth outcome?

**Comment by msschroeder** [comment]
@cafootitt Yes, I think that would be great! If you could mark it in the PNC data dictionary that would be great! I am going to close. And I would add to the issues for each task when hey are still vs livebirth
