### ISSUE TITLE
Implement PNC profile page if stillbirth or from day 29 onwards, if live birth

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#82]
The PNC profile changes at {delivery_date} + 29 days for the outcome of live birth. At 29 days, the child is removed from the PNC profile (and appears in the Child register list - separate issue to be created). Please reference this issue for profile page before 29 days: https://github.com/orgs/OpenSRP/projects/18. If the pregnancy outcome is a stillbirth, this is the PNC profile all the time.

<img width="252" alt="Screen Shot 2019-06-13 at 9 52 24 AM" src="https://user-images.githubusercontent.com/20777928/59487816-73bc6880-8e86-11e9-8aaa-c0ab8a7eeba1.png">

- [x] Back arrow or device back button takes user to the previous page they were viewing. If coming from the family profile page, the label should be "Return to family members"; if coming from the PNC register list, the label should be "Return to all PNC women"
- [x] Top right 3 dots menu opens menu of options (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/74)
- [x] Avatar or image of the woman if taken in registration form 
- [x] {first_name} {middle_name} {surname}, {age}
- [x] PNC day [{today} - {delivery_date}] [interpunct] {village_town} [interpunct] ID: {opensrp_id}
- [x] Record PNC visit button row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/75)
- [x] Medical history row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/76)
- [x] Upcoming services row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/77)
- [x] Family has services due/overdue row (already implemented)
- [x] Call FAB (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/80)
- [ ] This profile should appear both from the PNC register and from the All Families register.

------------------------------------------------------------------------------------------------------
- [x] **Same in BA**: Back arrow or device back button takes user to the previous page they were viewing. If coming from the family profile page, the label should be "Return to family members"; if coming from the PNC register list, the label should be "Return to all PNC women"
- [x] **Same in BA**: Top right 3 dots menu opens menu of options (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/74)
- [x] **Same in BA**: Avatar or image of the woman if taken in registration form
- [x] **Same in BA**: {first_name} {middle_name} {surname}, {age}
- [x] **Different values in BA**: PNC day [{today} - {delivery_date}] [interpunct] **{fam_village}** [interpunct] ID: {opensrp_id}
- [x] **Same in BA**: Record PNC visit button row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/75)
- [x] **Same in BA**: Medical history row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/76)
- [x] **Same in BA**: Upcoming services row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/77)
- [ ] **Same in BA**: Family has services due/overdue row (already implemented)
- [x] **Same in BA**: Call FAB (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/80)
- [ ] **Same in BA**: This profile should appear both from the PNC register and from the All Families register.

**Comment by cafootitt** [comment]
@msschroeder I updated this issue slightly, because this is the profile from delivery for women with the outcome of stillbirth.

**Comment by msschroeder** [comment]
QA 29 July 2019:
Remaining issues for BA:
- [x] **Same in BA**: Back arrow or device back button takes user to the previous page they were viewing. If coming from the family profile page, the label should be "Return to family members"; if coming from the PNC register list, the label should be "Return to all PNC women"
- [ ] **Same in BA**: Top right 3 dots menu opens menu of options (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/74)
- [ ] **Same in BA**: Record PNC visit button row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/75)
- [ ] **Same in BA**: Medical history row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/76)
- [ ] **Same in BA**: Upcoming services row (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/77)
- [ ] **Same in BA**: Family has services due/overdue row (already implemented)
- [ ] **Same in BA**: This profile should appear both from the PNC register and from the All Families register.

**Comment by paulinembabu** [comment]
Closing the issue requires all the profiles to be merged

**Comment by cafootitt** [comment]
I'm closing this and putting all clean up in this issue: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/284

**Comment by cafootitt** [comment]
https://github.com/OpenSRP/opensrp-client-chw-anc/issues/284 for all remaining clean up
